# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0002_auto_20170511_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.CharField(choices=[('NZ', 'nZ'), ('International', 'INTERNATIONAL'), ('Tech', 'TECH'), ('Sports', 'SPORTS')], max_length=30),
        ),
    ]
