# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0003_auto_20170512_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.CharField(choices=[('NZ', 'NZ'), ('International', 'International'), ('Tech', 'Tech'), ('Sports', 'Sports')], max_length=30),
        ),
    ]
